Algoritmo "Questao2"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 18/07/2019
Var
nota1, nota2, resultado: inteiro


Inicio
      nota1 <- 80
      nota2 <- 90
      resultado <- nota1 + nota2 /2
      escreval(resultado)


Fimalgoritmo